# Generated by Django 3.1.1 on 2020-09-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='cover_lettre',
            field=models.TextField(max_length=500),
        ),
    ]
