# Generated by Django 3.1.1 on 2020-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20200910_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='cover_lettre',
            new_name='cover_letter',
        ),
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
